export const SESSION = {
    LEVEL: undefined,
    DO_RENDER: false,
    FIRST_FREE_ID: 0,
    LAST_PLACED_DIAMOND: 0,
    TILE_RENDERER: undefined,
    TILE_CANVAS: undefined,
    TEXT_CANVAS: undefined,
    OBJECT_CANVAS: undefined,
    TILE_CTX: undefined,
    TEXT_CTX: undefined,
    OBJECT_CTX: undefined,
    SELECTED_TOOL_TYPE: undefined,
    SELECTED_TYLE_TYPE: undefined,
    SELECTED_OBJECT_TYPE: undefined,
    SELECTED_TEXT_TYPE: undefined,
    MOUSE_DOWN: false,
    RIGHT_MOUSE_DOWN: false,
    ALLOW_MULTIPLE_LEVELPOINTS: false,
    PLATFROM_PREVIEWS: false,
    WIND_PREVIEWS: false,
    COVER_PREVIEWS: false,
    MOUSE_POS_X: 0,
    MOUSE_POS_Y: 0,
    SELECTED_OBJECT_ID: undefined,
    SNAP_X: 16,
    SNAP_Y: 16,
    MOVE_HANDLE_OFFSET_X: 0,
    MOVE_HANDLE_OFFSET_Y: 0,
    LAST_PALCED_DOOR: 0,
    LAST_PLACED_SPAWN: 0,
    EDITOR_FUNCTION: 'tile-editor',

    SHOW_CONSOLE_DEBUG: false,
};