export const SESSION = {
    LEVEL: undefined,
    DO_RENDER: false,
    FIRST_FREE_ID: 0,
    LAST_PLACED_DIAMOND: 0,
    TILE_RENDERER: undefined,
    TILE_CANVAS: undefined,
    OBJECT_CANVAS: undefined,
    TILE_CTX: undefined,
    OBJECT_CTX: undefined,
    SELECTED_TOOL_TYPE: undefined,
    SELECTED_TYLE_TYPE: undefined,
    SELECTED_OBJECT_TYPE: undefined,
    MOUSE_DOWN: false,
    RIGHT_MOUSE_DOWN: false,
    ALLOW_MULTIPLE_LEVELPOINTS: false,
    PLATFROM_PREVIEWS: false,
    WIND_PREVIEWS: false,
    COVER_PREVIEWS: false,
    SHOW_CONSOLE_DEBUG: true,
    MOUSE_POS_X: 0,
    MOUSE_POS_Y: 0,
    SELECTED_OBJECT_ID: undefined,
};
