export const SESSION = {
    LEVEL: undefined,
    DO_RENDER: false,
    FIRST_FREE_ID: 0,
    LAST_PLACED_DIAMOND: 0,
    ALLOW_MULTIPLE_LEVELPOINTS: 0,
    TILE_RENDERER: undefined,
    TILE_CANVAS: undefined,
    OBJECT_CANVAS: undefined,
    TILE_CTX: undefined,
    OBJECT_CTX: undefined,
    SELECTED_TOOL_TYPE: undefined,
    SELECTED_TYLE_TYPE: undefined,
    SELECTED_OBJECT_TYPE: undefined,
    MOUSE_DOWN: false,
    RIGHT_MOUSE_DOWN: false,
};
